language: python
python:
  - "3.6"
install:
  - pip install pytest-cov pytest-xdist pytest-instafail pytest-pep8 pytest-spec
  - pip install .
  - pip install -r test_requirements.txt
# command to run tests
script: 
  - pytest
