name: psnprices

on:
  pull_request:
  push:
    branches:
      - master
      - drop-requests
  #schedule:
  #  - cron: "0 12 */5 * *"
jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build it

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7' # Limit to Python 3.7 because of python-coverage error
        architecture: 'x64'
    - run: make test_deps
    - run: make test

